 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run:
          name: "test"
          shell: powershell.exe
          command: |
                  choco install llvm cmake
                  refreshenv
                  clang++ --version
                  clang-tidy --version
                  clang-format --version
                  cmake --version
                  cl --version
